language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

virtualenv:
  system_site_packages: true

install: pip install -r requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script: python setup.py test
