cdef inline double square(double f)
cdef inline double mag_sq(double x, double y)
cdef inline double wrap_real(double L, double L_half, double r)
cdef inline unsigned int wrap(unsigned int M, int i)
cdef inline unsigned int wrap_inc(unsigned int M, unsigned int i)
cdef inline unsigned int wrap_dec(unsigned int M, unsigned int i)
